syntax = "proto3";

option java_multiple_files = true;
option java_package = "clientToImageServiceStubs";
option java_outer_classname = "ClientToImageServerProto";


package clientToImageService; // package do proto

// serviço com operações sobre números
service ClientToImageserver{
  rpc imageProcessing(stream Image) returns (ImgID);

  rpc DownloadImage(ImgID) returns (stream Image);

  rpc ConsultStatus(ImgID) returns (StatusInfo);

}

message Image{
  oneof Options {
    bytes block = 1;
    DataImage data = 2;
    string message = 3;
  }
}

message DataImage {
  string filename = 1;
}

message ImgID {
  string id = 1;
}

message StatusInfo {
  string id = 1;
  string status = 2;
  string filename = 3;
  string input_path = 4;
  string output_path = 5;
  string host = 6;
  string port = 7;
}
